# Generated by Django 4.0.4 on 2022-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title of an article')),
                ('short_text', models.TextField(max_length=500, verbose_name='first lines of an article')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='main photo')),
                ('date', models.DateTimeField()),
                ('url', models.URLField(max_length=250, verbose_name='url of an article')),
                ('sharing_count', models.IntegerField(verbose_name='number of sharing')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
