# Generated by Django 3.2.5 on 2022-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sharing_count',
            field=models.IntegerField(default=0, verbose_name='number of sharing'),
        ),
    ]
